### 식재로 등록
POST http://localhost:8080/api/v1/ingredient-stock
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "ingredientStockName": "왕만두",
  "ingredientStockCategory": "processed",
  "ingredientStockBoughtAt": "2026-01-13",
  "ingredientStockExpiredAt": "2028-10-24",
  "ingredientStockTotalCost": 15000,
  "ingredientStockTotalQuantity": 10,
  "ingredientStockUnit": "ea"
}

### 등록 식재료 조회
GET http://localhost:8080/api/v1/ingredient-stocks
Authorization: Bearer {{auth_token}}

### 식재료 정보 수정 (현재 수량 업데이트)
PATCH http://localhost:8080/api/v1/ingredient-stock
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "ingredientStockNo": 7,
  "ingredientStockUsedQuantity": 6
}