### 식재로 등록
POST http://localhost:8080/api/v1/ingredient-stock
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "ingredientStockName": "왕만두",
  "ingredientStockCategory": "processed",
  "ingredientStockBoughtAt": "2026-01-13",
  "ingredientStockExpiredAt": "2028-10-24",
  "ingredientStockTotalCost": 15000,
  "ingredientStockTotalQuantity": 10,
  "ingredientStockUnit": "ea"
}

### 등록 식재료 조회
GET http://localhost:8080/api/v1/ingredient-stocks
Authorization: Bearer {{auth_token}}

### 식재료 정보 수정 (현재 수량 업데이트)
PATCH http://localhost:8080/api/v1/ingredient-stock
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "ingredientStockNo": 7,
  "ingredientStockUsedQuantity": 6
}

### 식재료 알림 설정 (유통기한 임박 및 재고 부족 알림 생성)
POST http://localhost:8080/api/v1/ingredient-stock/notification
Authorization: Bearer {{auth_token}}

### 식재료 폐기 등록 (재고 감소 및 폐기 이력 생성)
POST http://localhost:8080/api/v1/disposal
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "ingredientStockNo": 40,
  "disposalQuantity": 40,
  "disposalReason": "유통기한 경과"
}