### 월별 식자재 지출 분석
GET http://localhost:8080/api/v1/statistics/monthly/1?yearMonth=2026-01

### 식자재별 비용 비중
GET http://localhost:8080/api/v1/statistics/ingreient/1

### 폐기 식자재 비용 분석
GET http://localhost:8080/api/v1/statistics/disposal/1

### 페기 식자재 비용 분석(기간별)
GET http://localhost:8080/api/v1/statistics/disposal/1?startDate=2026-01&endDate=2026-03

### 카테고리별 지출 분석
GET http://localhost:8080/api/v1/statistics/category/1

### 지출 대비 폐기율 산출
GET http://localhost:8080/api/v1/statistics/monthly-disposal/1