
### 회원 가입
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "userId": "testuser01",
  "password": "testuserpwd@",
  "nickname": "sinwooTest",
  "email": "testuser01@gmail.xom",
  "phoneNum": "01012345678",
  "birthdate": "2025-06-06"
}

### 로그인
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "userId": "testuser01",
  "password": "testuserpwd@"
}

> {%
    // 로그인 결과(응답) 중 accessToken을 auth_token 변수에 저장
    client.global.set("auth_token", response.body.data.accessToken);
%}

### UserID를 사용한 회원 정보 조회
GET http://localhost:8080/api/v1/users/testuser01
Authorization: Bearer {{auth_token}}
Accept: application/json

### 로그인 후 본인정보 조회
GET http://localhost:8080/api/v1/users/myinfo
Authorization: Bearer {{auth_token}}


### 로그아웃
POST http://localhost:8080/api/v1/auth/logout
Authorization: Bearer {{auth_token}}
Accept: application/json

> {%
    client.global.clearAll();
%}

### 회원정보 (email, phoneNum) 수정
PATCH http://localhost:8080/api/v1/users
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "email": "rlatlsdn98@gmail.com",
  "phoneNum": "010-9999-1192"
}

### 회원정보 (password) 수정
PATCH http://localhost:8080/api/v1/users/password
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "resentPassword": "testuserpwd@",
  "newPassword": "password#",
  "checkNewPassword": "password#"
}

### 회원탈퇴
DELETE http://localhost:8080/api/v1/users
Authorization: Bearer {{auth_token}}